### ISSUE TITLE
CSS tags

### ISSUE THREAD

**Issue by brissebrat** [sedoo/sedoo-portalgenerator#12]
Dans la page edition dataset, style de la ligne history à corriger (indication ISSUE ou UPDATE).
Ex : https://kascade-data.sedoo.fr/?editDatsId=14&datsId=14&project_name=KASCADE

Dans Mistrals, 4 classes étaient utilisées pour les tags : blue_tag, light_blue_tag, pink_tag et lightpink_tag

**Comment by brissebrat** [comment]
Utilisé également sur la ligne DOI
Et sur la page News

**Comment by pvert** [comment]
corrections sur release 1.2.0 à venir.
